version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 8012:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./:/var/www
      - ./storage/logs:/var/log
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    ports:
      - 33065:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      #      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}